services:
- type: web
  name: another rizz
  runtime: node
  repo: https://github.com/FrogiesArcade/FrogiesArcade-v2-Portable
  plan: free
  region: oregon
  buildCommand: npm i
  startCommand: node index.js
version: "1"
